info:
  contact: {}
  description: Xpertise Scholar
  title: Xpertise Scholar Golang Backend
  version: "1.0"
paths:
  /admin/authorize/all:
    get:
      description: 获取用户申请条目
      responses:
        "200":
          description: '{"success": true, "message": "获取条目成功。", "data": "model.AuthorizationRequest的所有信息"}'
          schema:
            type: string
      tags:
      - admin
  /admin/authorize/deal:
    post:
      description: 处理用户申请认证
      parameters:
      - description: 用户申请认证ID
        in: formData
        name: authreq_id
        required: true
        type: string
      - description: Accept/Reject
        in: formData
        name: action
        required: true
        type: string
      - description: 对应作者ID
        in: formData
        name: author_id
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "已通过认证请求。"}'
          schema:
            type: string
      tags:
      - admin
  /admin/authorize/request:
    post:
      description: 发送请求认证
      parameters:
      - description: 用户名
        in: formData
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "申请认证成功。"}'
          schema:
            type: string
      tags:
      - admin
  /branch/comment/create:
    post:
      description: 创建一条评论
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 文献ID
        in: formData
        name: paper_id
        required: true
        type: string
      - description: 评论内容
        in: formData
        name: content
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "用户评论成功"}'
          schema:
            type: string
      tags:
      - branch
  /branch/comment/operate:
    post:
      description: 操作评论
      parameters:
      - description: 评论ID
        in: formData
        name: username
        required: true
        type: string
      - description: 对评论的操作方法，1为置顶，2为取消置顶，3为删除
        in: formData
        name: method
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "操作成功"}'
          schema:
            type: string
      tags:
      - branch
  /portal/add_to_column:
    post:
      description: 添加某篇文章到专栏
      parameters:
      - description: 文献ID
        in: formData
        name: paper_id
        required: true
        type: string
      - description: 专栏ID
        in: formData
        name: column_id
        required: true
        type: string
      responses:
        "200":
          description: '{"success":true, "message":"添加到专栏成功"}'
          schema:
            type: string
      tags:
      - portal
  /portal/create_column:
    post:
      description: 创建一个专栏
      parameters:
      - description: 作者ID
        in: formData
        name: author_id
        required: true
        type: string
      - description: 专栏名字
        in: formData
        name: column_name
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "创建专栏成功"}'
          schema:
            type: string
      tags:
      - portal
  /portal/list_all_from_column:
    post:
      description: 获取某个专栏的所有内容
      parameters:
      - description: 专栏ID
        in: formData
        name: column_id
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "查找成功", "data": "专栏中的所有论文ID"}'
          schema:
            type: string
      tags:
      - portal
  /portal/remove_from_column:
    post:
      description: 删除专栏中的某条论文
      parameters:
      - description: 专栏ID
        in: formData
        name: column_id
        required: true
        type: string
      - description: 论文ID
        in: formData
        name: paper_id
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "删除成功"}'
          schema:
            type: string
      tags:
      - portal
  /user/authorize/get:
    post:
      description: 获取用户的（所有）请求认证
      parameters:
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "获取申请信息成功。", "data": "请求认证的所有信息。"}'
          schema:
            type: string
      tags:
      - user
  /user/authorize/read:
    post:
      description: 已读一条请求认证
      parameters:
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      - description: 请求认证ID
        in: formData
        name: authreq_id
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "标记已读成功！"}'
          schema:
            type: string
      tags:
      - user
  /user/favorite/add:
    post:
      description: 添加收藏
      parameters:
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      - description: 文献ID
        in: formData
        name: paper_id
        required: true
        type: string
      - description: 文献描述
        in: formData
        name: paper_info
        required: true
        type: string
      responses:
        "200":
          description: '{"success":true, "message":"收藏成功"}'
          schema:
            type: string
      tags:
      - user
  /user/favorite/list:
    post:
      description: 获取收藏列表
      parameters:
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: '{"success":true, "message":"查询成功","data":"user的所有收藏"}'
          schema:
            type: string
      tags:
      - user
  /user/favorite/remove:
    post:
      description: 移除收藏
      parameters:
      - description: 收藏ID
        in: formData
        name: favor_id
        required: true
        type: string
      responses:
        "200":
          description: '{"success":true, "message":"删除成功"}'
          schema:
            type: string
      tags:
      - user
  /user/info:
    post:
      description: 查看用户个人信息
      parameters:
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "查看用户信息成功", "data": "model.User的所有信息"}'
          schema:
            type: string
      tags:
      - user
  /user/login:
    post:
      description: 用户登录
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "登录成功", "data": "model.User的所有信息"}'
          schema:
            type: string
      tags:
      - user
  /user/modify:
    post:
      description: 修改用户信息
      parameters:
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 原密码
        in: formData
        name: password1
        required: true
        type: string
      - description: 新密码
        in: formData
        name: password2
        required: true
        type: string
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      - description: 个人信息
        in: formData
        name: info
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "登录成功", "data": "model.User的所有信息"}'
          schema:
            type: string
      tags:
      - user
  /user/register:
    post:
      description: 注册
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码1
        in: formData
        name: password1
        required: true
        type: string
      - description: 密码2
        in: formData
        name: password2
        required: true
        type: string
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      - description: 个人信息
        in: formData
        name: info
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "用户创建成功"}'
          schema:
            type: string
      tags:
      - user
  /user/wish/add:
    post:
      description: 添加至清单
      parameters:
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      - description: 文献ID
        in: formData
        name: paper_id
        required: true
        type: string
      - description: 文献辩题
        in: formData
        name: title
        required: true
        type: string
      responses:
        "200":
          description: '{"success":true, "message":"已添加至清单"}'
          schema:
            type: string
      tags:
      - user
  /user/wish/list:
    post:
      description: 获取收藏列表
      parameters:
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: '{"success":true, "message":"查询成功","data":"user的清单"}'
          schema:
            type: string
      tags:
      - user
  /user/wish/remove:
    post:
      description: 移出清单
      parameters:
      - description: 心愿ID
        in: formData
        name: wish_id
        required: true
        type: string
      responses:
        "200":
          description: '{"success":true, "message":"已移出清单"}'
          schema:
            type: string
      tags:
      - user
schemes:
- http
- https
swagger: "2.0"
